// This file is generated by scripts/generate-fonts.ts from content/design.json.
// Edit design.json (typography) and run `npm run generate-fonts` instead of editing it.
// The Revaltus platform rewrites it when the site fonts change (Design Studio / Theme Studio).

import type { CSSProperties } from 'react'
import { Plus_Jakarta_Sans, Public_Sans, Fraunces, Geist_Mono } from 'next/font/google'

const font0 = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-heading-loaded',
  display: 'swap',
})

const font1 = Public_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-body-loaded',
  display: 'swap',
})

const font2 = Fraunces({
  subsets: ['latin'],
  weight: ['400', '500'],
  style: ['normal', 'italic'],
  variable: '--font-accent-loaded',
  display: 'swap',
})

const font3 = Geist_Mono({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-mono-loaded',
  display: 'swap',
})

/** next/font variable classes for <html className>. */
export const fontVariables = `${font0.variable} ${font1.variable} ${font2.variable} ${font3.variable}`

/** Roles sharing a family point at the loaded variable (applied as <html style>). */
export const fontAliases: CSSProperties = {}
